<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>10 Регрессионный анализ | АнДан 2021: стартовая программа</title>
  <meta name="description" content="10 Регрессионный анализ | АнДан 2021: стартовая программа" />
  <meta name="generator" content="bookdown 0.22 and GitBook 2.6.7" />

  <meta property="og:title" content="10 Регрессионный анализ | АнДан 2021: стартовая программа" />
  <meta property="og:type" content="book" />
  
  
  
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="10 Регрессионный анализ | АнДан 2021: стартовая программа" />
  
  
  

<meta name="author" content="А. Ангельгардт, М. Серветник, Ю. Мартысенко, А. Котликова" />



  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="anova-a-k-a-дисперсионный-анализ.html"/>

<script src="libs/header-attrs-2.9/header-attrs.js"></script>
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />









<link href="libs/pagedtable-1.1/css/pagedtable.css" rel="stylesheet" />
<script src="libs/pagedtable-1.1/js/pagedtable.js"></script>
<link href="libs/anchor-sections-1.0.1/anchor-sections.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.0.1/anchor-sections.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">2021 Андан стартовая</a></li>

<li class="divider"></li>
<li class="chapter" data-level="1" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i><b>1</b> О курсе</a></li>
<li class="chapter" data-level="2" data-path="знакомство-с-rstudio.html"><a href="знакомство-с-rstudio.html"><i class="fa fa-check"></i><b>2</b> Знакомство с RStudio</a>
<ul>
<li class="chapter" data-level="2.1" data-path="знакомство-с-rstudio.html"><a href="знакомство-с-rstudio.html#знакомство-с-rstudio-1"><i class="fa fa-check"></i><b>2.1</b> Знакомство с RStudio</a></li>
<li class="chapter" data-level="2.2" data-path="знакомство-с-rstudio.html"><a href="знакомство-с-rstudio.html#горячие-клавиши"><i class="fa fa-check"></i><b>2.2</b> Горячие клавиши</a></li>
<li class="chapter" data-level="2.3" data-path="знакомство-с-rstudio.html"><a href="знакомство-с-rstudio.html#гайды-по-стилю-r"><i class="fa fa-check"></i><b>2.3</b> Гайды по стилю R</a></li>
<li class="chapter" data-level="2.4" data-path="знакомство-с-rstudio.html"><a href="знакомство-с-rstudio.html#рабочая-папка"><i class="fa fa-check"></i><b>2.4</b> Рабочая папка</a></li>
<li class="chapter" data-level="2.5" data-path="знакомство-с-rstudio.html"><a href="знакомство-с-rstudio.html#открываем-файл"><i class="fa fa-check"></i><b>2.5</b> Открываем файл</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="введение-в-r.html"><a href="введение-в-r.html"><i class="fa fa-check"></i><b>3</b> Введение в R</a>
<ul>
<li class="chapter" data-level="3.1" data-path="введение-в-r.html"><a href="введение-в-r.html#общее"><i class="fa fa-check"></i><b>3.1</b> Общее</a></li>
<li class="chapter" data-level="3.2" data-path="введение-в-r.html"><a href="введение-в-r.html#типы-данных"><i class="fa fa-check"></i><b>3.2</b> Типы данных</a>
<ul>
<li class="chapter" data-level="3.2.1" data-path="введение-в-r.html"><a href="введение-в-r.html#целое-число-integer"><i class="fa fa-check"></i><b>3.2.1</b> Целое число — integer</a></li>
<li class="chapter" data-level="3.2.2" data-path="введение-в-r.html"><a href="введение-в-r.html#число-с-плавающей-точкой-double"><i class="fa fa-check"></i><b>3.2.2</b> Число с плавающей точкой — double</a></li>
<li class="chapter" data-level="3.2.3" data-path="введение-в-r.html"><a href="введение-в-r.html#комплексные-числа-complex"><i class="fa fa-check"></i><b>3.2.3</b> Комплексные числа — complex</a></li>
<li class="chapter" data-level="3.2.4" data-path="введение-в-r.html"><a href="введение-в-r.html#символьный-тип-данных-строки-character"><i class="fa fa-check"></i><b>3.2.4</b> Символьный тип данных (строки) — character</a></li>
<li class="chapter" data-level="3.2.5" data-path="введение-в-r.html"><a href="введение-в-r.html#фактор-factor"><i class="fa fa-check"></i><b>3.2.5</b> Фактор — factor</a></li>
<li class="chapter" data-level="3.2.6" data-path="введение-в-r.html"><a href="введение-в-r.html#упорядоченный-фактор-ordered-factor"><i class="fa fa-check"></i><b>3.2.6</b> Упорядоченный фактор — ordered factor</a></li>
<li class="chapter" data-level="3.2.7" data-path="введение-в-r.html"><a href="введение-в-r.html#логические-boolean"><i class="fa fa-check"></i><b>3.2.7</b> Логические — boolean</a></li>
<li class="chapter" data-level="3.2.8" data-path="введение-в-r.html"><a href="введение-в-r.html#даты"><i class="fa fa-check"></i><b>3.2.8</b> Даты</a></li>
<li class="chapter" data-level="3.2.9" data-path="введение-в-r.html"><a href="введение-в-r.html#пропущенные-значения-missing-values"><i class="fa fa-check"></i><b>3.2.9</b> Пропущенные значения — missing values</a></li>
</ul></li>
<li class="chapter" data-level="3.3" data-path="введение-в-r.html"><a href="введение-в-r.html#структуры-данных"><i class="fa fa-check"></i><b>3.3</b> Структуры данных</a>
<ul>
<li class="chapter" data-level="3.3.1" data-path="введение-в-r.html"><a href="введение-в-r.html#вектор"><i class="fa fa-check"></i><b>3.3.1</b> Вектор</a></li>
<li class="chapter" data-level="3.3.2" data-path="введение-в-r.html"><a href="введение-в-r.html#матрицы"><i class="fa fa-check"></i><b>3.3.2</b> Матрицы</a></li>
<li class="chapter" data-level="3.3.3" data-path="введение-в-r.html"><a href="введение-в-r.html#списки"><i class="fa fa-check"></i><b>3.3.3</b> Списки</a></li>
<li class="chapter" data-level="3.3.4" data-path="введение-в-r.html"><a href="введение-в-r.html#дата-фреймы"><i class="fa fa-check"></i><b>3.3.4</b> Дата фреймы</a></li>
<li class="chapter" data-level="3.3.5" data-path="введение-в-r.html"><a href="введение-в-r.html#другие"><i class="fa fa-check"></i><b>3.3.5</b> Другие</a></li>
</ul></li>
<li class="chapter" data-level="3.4" data-path="введение-в-r.html"><a href="введение-в-r.html#функции-и-простые-действия-с-данными"><i class="fa fa-check"></i><b>3.4</b> Функции и простые действия с данными</a></li>
<li class="chapter" data-level="3.5" data-path="введение-в-r.html"><a href="введение-в-r.html#задания-для-тренировки"><i class="fa fa-check"></i><b>3.5</b> Задания для тренировки</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="фильтрация-строк-и-столбцов-в-base-r-введение-в-data-table.html"><a href="фильтрация-строк-и-столбцов-в-base-r-введение-в-data-table.html"><i class="fa fa-check"></i><b>4</b> Фильтрация строк и столбцов в base R. Введение в data.table</a>
<ul>
<li class="chapter" data-level="4.1" data-path="фильтрация-строк-и-столбцов-в-base-r-введение-в-data-table.html"><a href="фильтрация-строк-и-столбцов-в-base-r-введение-в-data-table.html#фильтрация-строк-и-столбцов-в-base-r"><i class="fa fa-check"></i><b>4.1</b> Фильтрация строк и столбцов в base R</a>
<ul>
<li class="chapter" data-level="4.1.1" data-path="фильтрация-строк-и-столбцов-в-base-r-введение-в-data-table.html"><a href="фильтрация-строк-и-столбцов-в-base-r-введение-в-data-table.html#фильтрация-вектора-по-условию"><i class="fa fa-check"></i><b>4.1.1</b> Фильтрация вектора по условию</a></li>
<li class="chapter" data-level="4.1.2" data-path="фильтрация-строк-и-столбцов-в-base-r-введение-в-data-table.html"><a href="фильтрация-строк-и-столбцов-в-base-r-введение-в-data-table.html#фильтрация-дата.фрейма-по-условию"><i class="fa fa-check"></i><b>4.1.2</b> Фильтрация дата.фрейма по условию</a></li>
<li class="chapter" data-level="4.1.3" data-path="фильтрация-строк-и-столбцов-в-base-r-введение-в-data-table.html"><a href="фильтрация-строк-и-столбцов-в-base-r-введение-в-data-table.html#фильтрация-по-результату-функции"><i class="fa fa-check"></i><b>4.1.3</b> Фильтрация по результату функции</a></li>
<li class="chapter" data-level="4.1.4" data-path="фильтрация-строк-и-столбцов-в-base-r-введение-в-data-table.html"><a href="фильтрация-строк-и-столбцов-в-base-r-введение-в-data-table.html#фильтрация-для-группировки"><i class="fa fa-check"></i><b>4.1.4</b> Фильтрация для группировки</a></li>
<li class="chapter" data-level="4.1.5" data-path="фильтрация-строк-и-столбцов-в-base-r-введение-в-data-table.html"><a href="фильтрация-строк-и-столбцов-в-base-r-введение-в-data-table.html#введение-в-data.table"><i class="fa fa-check"></i><b>4.1.5</b> Введение в data.table</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="5" data-path="cтатистические-критерии-корреляции.html"><a href="cтатистические-критерии-корреляции.html"><i class="fa fa-check"></i><b>5</b> Cтатистические критерии, корреляции</a>
<ul>
<li class="chapter" data-level="5.1" data-path="cтатистические-критерии-корреляции.html"><a href="cтатистические-критерии-корреляции.html#введение"><i class="fa fa-check"></i><b>5.1</b> Введение</a></li>
<li class="chapter" data-level="5.2" data-path="cтатистические-критерии-корреляции.html"><a href="cтатистические-критерии-корреляции.html#goodness-of-fit-tests"><i class="fa fa-check"></i><b>5.2</b> Goodness-of-fit tests</a>
<ul>
<li class="chapter" data-level="5.2.1" data-path="cтатистические-критерии-корреляции.html"><a href="cтатистические-критерии-корреляции.html#биномиальный-критерий"><i class="fa fa-check"></i><b>5.2.1</b> Биномиальный критерий</a></li>
<li class="chapter" data-level="5.2.2" data-path="cтатистические-критерии-корреляции.html"><a href="cтатистические-критерии-корреляции.html#критерий-хи-квадрат"><i class="fa fa-check"></i><b>5.2.2</b> Критерий Хи-квадрат</a></li>
</ul></li>
<li class="chapter" data-level="5.3" data-path="cтатистические-критерии-корреляции.html"><a href="cтатистические-критерии-корреляции.html#тестирование-взаимосвязи-между-двумя-категориальными-переменными"><i class="fa fa-check"></i><b>5.3</b> Тестирование взаимосвязи между двумя категориальными переменными</a>
<ul>
<li class="chapter" data-level="5.3.1" data-path="cтатистические-критерии-корреляции.html"><a href="cтатистические-критерии-корреляции.html#таблицы-сопряжённости"><i class="fa fa-check"></i><b>5.3.1</b> таблицы сопряжённости</a></li>
<li class="chapter" data-level="5.3.2" data-path="cтатистические-критерии-корреляции.html"><a href="cтатистические-критерии-корреляции.html#тест-фишера"><i class="fa fa-check"></i><b>5.3.2</b> Тест Фишера</a></li>
<li class="chapter" data-level="5.3.3" data-path="cтатистические-критерии-корреляции.html"><a href="cтатистические-критерии-корреляции.html#добавляем-хи-квадрат"><i class="fa fa-check"></i><b>5.3.3</b> Добавляем Хи-квадрат</a></li>
</ul></li>
<li class="chapter" data-level="5.4" data-path="cтатистические-критерии-корреляции.html"><a href="cтатистические-критерии-корреляции.html#критерии-для-порядковых-или-ненормально-распределённых-переменных"><i class="fa fa-check"></i><b>5.4</b> Критерии для порядковых или ненормально распределённых переменных</a>
<ul>
<li class="chapter" data-level="5.4.1" data-path="cтатистические-критерии-корреляции.html"><a href="cтатистические-критерии-корреляции.html#тест-манна-уитни"><i class="fa fa-check"></i><b>5.4.1</b> Тест Манна-Уитни</a></li>
<li class="chapter" data-level="5.4.2" data-path="cтатистические-критерии-корреляции.html"><a href="cтатистические-критерии-корреляции.html#t-критерий-вилкоксона-для-зависимых-выборок"><i class="fa fa-check"></i><b>5.4.2</b> T-критерий Вилкоксона для зависимых выборок</a></li>
</ul></li>
<li class="chapter" data-level="5.5" data-path="cтатистические-критерии-корреляции.html"><a href="cтатистические-критерии-корреляции.html#сравнение-средних"><i class="fa fa-check"></i><b>5.5</b> Сравнение средних</a>
<ul>
<li class="chapter" data-level="5.5.1" data-path="cтатистические-критерии-корреляции.html"><a href="cтатистические-критерии-корреляции.html#t-критерий-стьюдента-для-независимых-выборок"><i class="fa fa-check"></i><b>5.5.1</b> t-критерий Стьюдента для независимых выборок</a></li>
<li class="chapter" data-level="5.5.2" data-path="cтатистические-критерии-корреляции.html"><a href="cтатистические-критерии-корреляции.html#t-критерий-стьюдента-для-зависимых-выборок"><i class="fa fa-check"></i><b>5.5.2</b> t-критерий Стьюдента для зависимых выборок</a></li>
</ul></li>
<li class="chapter" data-level="5.6" data-path="cтатистические-критерии-корреляции.html"><a href="cтатистические-критерии-корреляции.html#коэффициенты-корреляции"><i class="fa fa-check"></i><b>5.6</b> Коэффициенты корреляции</a>
<ul>
<li class="chapter" data-level="5.6.1" data-path="cтатистические-критерии-корреляции.html"><a href="cтатистические-критерии-корреляции.html#корреляция-пирсона"><i class="fa fa-check"></i><b>5.6.1</b> Корреляция Пирсона</a></li>
<li class="chapter" data-level="5.6.2" data-path="cтатистические-критерии-корреляции.html"><a href="cтатистические-критерии-корреляции.html#ранговые-коэффициенты-спирман-и-кендалл"><i class="fa fa-check"></i><b>5.6.2</b> Ранговые коэффициенты: Спирман и Кендалл</a></li>
</ul></li>
<li class="chapter" data-level="5.7" data-path="cтатистические-критерии-корреляции.html"><a href="cтатистические-критерии-корреляции.html#бонус-визуализация-корреляционной-матрицы"><i class="fa fa-check"></i><b>5.7</b> Бонус: визуализация корреляционной матрицы</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="продолжаем-с-data-table.html"><a href="продолжаем-с-data-table.html"><i class="fa fa-check"></i><b>6</b> Продолжаем с data.table</a>
<ul>
<li class="chapter" data-level="6.1" data-path="продолжаем-с-data-table.html"><a href="продолжаем-с-data-table.html#продолжаем-с-data.table-1"><i class="fa fa-check"></i><b>6.1</b> Продолжаем с data.table</a>
<ul>
<li class="chapter" data-level="6.1.1" data-path="продолжаем-с-data-table.html"><a href="продолжаем-с-data-table.html#счёт-элементов-с-помощью-.n"><i class="fa fa-check"></i><b>6.1.1</b> Счёт элементов с помощью .N</a></li>
<li class="chapter" data-level="6.1.2" data-path="продолжаем-с-data-table.html"><a href="продолжаем-с-data-table.html#несколько-группировок"><i class="fa fa-check"></i><b>6.1.2</b> Несколько группировок</a></li>
<li class="chapter" data-level="6.1.3" data-path="продолжаем-с-data-table.html"><a href="продолжаем-с-data-table.html#несколько-выражений"><i class="fa fa-check"></i><b>6.1.3</b> Несколько выражений</a></li>
<li class="chapter" data-level="6.1.4" data-path="продолжаем-с-data-table.html"><a href="продолжаем-с-data-table.html#имена-колонок"><i class="fa fa-check"></i><b>6.1.4</b> Имена колонок</a></li>
</ul></li>
<li class="chapter" data-level="6.2" data-path="продолжаем-с-data-table.html"><a href="продолжаем-с-data-table.html#указание-имён-при-создании-колонок"><i class="fa fa-check"></i><b>6.2</b> Указание имён при создании колонок</a></li>
<li class="chapter" data-level="6.3" data-path="продолжаем-с-data-table.html"><a href="продолжаем-с-data-table.html#вечер-в-хату-вектор-в-colnames"><i class="fa fa-check"></i><b>6.3</b> Вечер в хату, вектор в <code>colnames()</code></a></li>
<li class="chapter" data-level="6.4" data-path="продолжаем-с-data-table.html"><a href="продолжаем-с-data-table.html#setnames-из-библиотеки-data.table"><i class="fa fa-check"></i><b>6.4</b> <code>setnames()</code> из библиотеки <code>data.table</code></a>
<ul>
<li class="chapter" data-level="6.4.1" data-path="продолжаем-с-data-table.html"><a href="продолжаем-с-data-table.html#новый-дата.тейбл-или-колонка-в-существующем"><i class="fa fa-check"></i><b>6.4.1</b> Новый дата.тейбл или колонка в существующем?</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="7" data-path="визуализация-данных-с-ggplot2.html"><a href="визуализация-данных-с-ggplot2.html"><i class="fa fa-check"></i><b>7</b> Визуализация данных с <code>ggplot2</code></a>
<ul>
<li class="chapter" data-level="7.1" data-path="визуализация-данных-с-ggplot2.html"><a href="визуализация-данных-с-ggplot2.html#визуализация-это-зачем"><i class="fa fa-check"></i><b>7.1</b> Визуализация это зачем?</a></li>
<li class="chapter" data-level="7.2" data-path="визуализация-данных-с-ggplot2.html"><a href="визуализация-данных-с-ggplot2.html#философия-a-layered-grammar-of-graphics"><i class="fa fa-check"></i><b>7.2</b> Философия A Layered Grammar of Graphics</a></li>
<li class="chapter" data-level="7.3" data-path="визуализация-данных-с-ggplot2.html"><a href="визуализация-данных-с-ggplot2.html#экшон"><i class="fa fa-check"></i><b>7.3</b> Экшон</a>
<ul>
<li class="chapter" data-level="7.3.1" data-path="визуализация-данных-с-ggplot2.html"><a href="визуализация-данных-с-ggplot2.html#пакеты"><i class="fa fa-check"></i><b>7.3.1</b> Пакеты</a></li>
<li class="chapter" data-level="7.3.2" data-path="визуализация-данных-с-ggplot2.html"><a href="визуализация-данных-с-ggplot2.html#данные"><i class="fa fa-check"></i><b>7.3.2</b> Данные</a></li>
<li class="chapter" data-level="7.3.3" data-path="визуализация-данных-с-ggplot2.html"><a href="визуализация-данных-с-ggplot2.html#строим-базовый-график"><i class="fa fa-check"></i><b>7.3.3</b> Строим базовый график</a></li>
<li class="chapter" data-level="7.3.4" data-path="визуализация-данных-с-ggplot2.html"><a href="визуализация-данных-с-ggplot2.html#ищем-более-сложные-закономерности"><i class="fa fa-check"></i><b>7.3.4</b> Ищем более сложные закономерности</a></li>
<li class="chapter" data-level="7.3.5" data-path="визуализация-данных-с-ggplot2.html"><a href="визуализация-данных-с-ggplot2.html#важное-замечание-о-визуализации"><i class="fa fa-check"></i><b>7.3.5</b> Важное замечание о визуализации</a></li>
<li class="chapter" data-level="7.3.6" data-path="визуализация-данных-с-ggplot2.html"><a href="визуализация-данных-с-ggplot2.html#инструменты-встроенной-статистической-обработки"><i class="fa fa-check"></i><b>7.3.6</b> Инструменты встроенной статистической обработки</a></li>
<li class="chapter" data-level="7.3.7" data-path="визуализация-данных-с-ggplot2.html"><a href="визуализация-данных-с-ggplot2.html#настраиваем-график"><i class="fa fa-check"></i><b>7.3.7</b> Настраиваем график</a></li>
<li class="chapter" data-level="7.3.8" data-path="визуализация-данных-с-ggplot2.html"><a href="визуализация-данных-с-ggplot2.html#сохранение-графиков"><i class="fa fa-check"></i><b>7.3.8</b> Сохранение графиков</a></li>
</ul></li>
<li class="chapter" data-level="7.4" data-path="визуализация-данных-с-ggplot2.html"><a href="визуализация-данных-с-ggplot2.html#файнал-босс"><i class="fa fa-check"></i><b>7.4</b> Файнал босс</a></li>
<li class="chapter" data-level="7.5" data-path="визуализация-данных-с-ggplot2.html"><a href="визуализация-данных-с-ggplot2.html#конклюжон"><i class="fa fa-check"></i><b>7.5</b> Конклюжон</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="слияние-и-преобразование-табличных-данных.html"><a href="слияние-и-преобразование-табличных-данных.html"><i class="fa fa-check"></i><b>8</b> Слияние и преобразование табличных данных</a>
<ul>
<li class="chapter" data-level="8.1" data-path="слияние-и-преобразование-табличных-данных.html"><a href="слияние-и-преобразование-табличных-данных.html#слияние-и-преобразование-табличных-данных-1"><i class="fa fa-check"></i><b>8.1</b> Слияние и преобразование табличных данных</a>
<ul>
<li class="chapter" data-level="8.1.1" data-path="слияние-и-преобразование-табличных-данных.html"><a href="слияние-и-преобразование-табличных-данных.html#соединение-двух-таблиц-в-одну-простой-случай."><i class="fa fa-check"></i><b>8.1.1</b> Соединение двух таблиц в одну: простой случай.</a></li>
<li class="chapter" data-level="8.1.2" data-path="слияние-и-преобразование-табличных-данных.html"><a href="слияние-и-преобразование-табличных-данных.html#merge-и-четыре-разных-соединения"><i class="fa fa-check"></i><b>8.1.2</b> <code>merge()</code> и четыре разных соединения</a></li>
<li class="chapter" data-level="8.1.3" data-path="слияние-и-преобразование-табличных-данных.html"><a href="слияние-и-преобразование-табличных-данных.html#inner-join"><i class="fa fa-check"></i><b>8.1.3</b> Inner join</a></li>
<li class="chapter" data-level="8.1.4" data-path="слияние-и-преобразование-табличных-данных.html"><a href="слияние-и-преобразование-табличных-данных.html#outer-join"><i class="fa fa-check"></i><b>8.1.4</b> Outer join</a></li>
<li class="chapter" data-level="8.1.5" data-path="слияние-и-преобразование-табличных-данных.html"><a href="слияние-и-преобразование-табличных-данных.html#left-join"><i class="fa fa-check"></i><b>8.1.5</b> Left join</a></li>
<li class="chapter" data-level="8.1.6" data-path="слияние-и-преобразование-табличных-данных.html"><a href="слияние-и-преобразование-табличных-данных.html#right-join"><i class="fa fa-check"></i><b>8.1.6</b> Right join</a></li>
<li class="chapter" data-level="8.1.7" data-path="слияние-и-преобразование-табличных-данных.html"><a href="слияние-и-преобразование-табличных-данных.html#широкие-или-длинные-данные"><i class="fa fa-check"></i><b>8.1.7</b> Широкие или длинные данные</a></li>
<li class="chapter" data-level="8.1.8" data-path="слияние-и-преобразование-табличных-данных.html"><a href="слияние-и-преобразование-табличных-данных.html#из-широких-в-длинные-melt"><i class="fa fa-check"></i><b>8.1.8</b> Из широких в длинные: <code>melt()</code></a></li>
<li class="chapter" data-level="8.1.9" data-path="слияние-и-преобразование-табличных-данных.html"><a href="слияние-и-преобразование-табличных-данных.html#качественные-вина"><i class="fa fa-check"></i><b>8.1.9</b> Качественные вина</a></li>
<li class="chapter" data-level="8.1.10" data-path="слияние-и-преобразование-табличных-данных.html"><a href="слияние-и-преобразование-табличных-данных.html#из-длинных-в-широкие-dcast"><i class="fa fa-check"></i><b>8.1.10</b> Из длинных в широкие: <code>dcast()</code></a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="9" data-path="anova-a-k-a-дисперсионный-анализ.html"><a href="anova-a-k-a-дисперсионный-анализ.html"><i class="fa fa-check"></i><b>9</b> ANOVA a.k.a. Дисперсионный анализ</a>
<ul>
<li class="chapter" data-level="9.1" data-path="anova-a-k-a-дисперсионный-анализ.html"><a href="anova-a-k-a-дисперсионный-анализ.html#зачем-нужен-дисперсионный-анализ"><i class="fa fa-check"></i><b>9.1</b> Зачем нужен дисперсионный анализ?</a>
<ul>
<li class="chapter" data-level="9.1.1" data-path="anova-a-k-a-дисперсионный-анализ.html"><a href="anova-a-k-a-дисперсионный-анализ.html#проблема-множественных-сравнений"><i class="fa fa-check"></i><b>9.1.1</b> Проблема множественных сравнений</a></li>
<li class="chapter" data-level="9.1.2" data-path="anova-a-k-a-дисперсионный-анализ.html"><a href="anova-a-k-a-дисперсионный-анализ.html#идея-дисперсионного-анализа"><i class="fa fa-check"></i><b>9.1.2</b> Идея дисперсионного анализа</a></li>
</ul></li>
<li class="chapter" data-level="9.2" data-path="anova-a-k-a-дисперсионный-анализ.html"><a href="anova-a-k-a-дисперсионный-анализ.html#однофакторный-дисперсионный-анализ"><i class="fa fa-check"></i><b>9.2</b> Однофакторный дисперсионный анализ</a>
<ul>
<li class="chapter" data-level="9.2.1" data-path="anova-a-k-a-дисперсионный-анализ.html"><a href="anova-a-k-a-дисперсионный-анализ.html#структура-изменчивости"><i class="fa fa-check"></i><b>9.2.1</b> Структура изменчивости</a></li>
<li class="chapter" data-level="9.2.2" data-path="anova-a-k-a-дисперсионный-анализ.html"><a href="anova-a-k-a-дисперсионный-анализ.html#тестирование-значимости-фактора"><i class="fa fa-check"></i><b>9.2.2</b> Тестирование значимости фактора</a></li>
<li class="chapter" data-level="9.2.3" data-path="anova-a-k-a-дисперсионный-анализ.html"><a href="anova-a-k-a-дисперсионный-анализ.html#данные-1"><i class="fa fa-check"></i><b>9.2.3</b> Данные</a></li>
<li class="chapter" data-level="9.2.4" data-path="anova-a-k-a-дисперсионный-анализ.html"><a href="anova-a-k-a-дисперсионный-анализ.html#дисперсионный-анализ-в-r"><i class="fa fa-check"></i><b>9.2.4</b> Дисперсионный анализ в R</a></li>
<li class="chapter" data-level="9.2.5" data-path="anova-a-k-a-дисперсионный-анализ.html"><a href="anova-a-k-a-дисперсионный-анализ.html#post-hoc-тесты"><i class="fa fa-check"></i><b>9.2.5</b> Post hoc тесты</a></li>
</ul></li>
<li class="chapter" data-level="9.3" data-path="anova-a-k-a-дисперсионный-анализ.html"><a href="anova-a-k-a-дисперсионный-анализ.html#многофакторный-дисперсионный-анализ"><i class="fa fa-check"></i><b>9.3</b> Многофакторный дисперсионный анализ</a></li>
<li class="chapter" data-level="9.4" data-path="anova-a-k-a-дисперсионный-анализ.html"><a href="anova-a-k-a-дисперсионный-анализ.html#многофакторный-дисперсионный-анализ-без-взаимодействия-в-r"><i class="fa fa-check"></i><b>9.4</b> Многофакторный дисперсионный анализ без взаимодействия в R</a>
<ul>
<li class="chapter" data-level="9.4.1" data-path="anova-a-k-a-дисперсионный-анализ.html"><a href="anova-a-k-a-дисперсионный-анализ.html#многофакторный-дисперсионный-анализ-со-взаимодействием-в-r"><i class="fa fa-check"></i><b>9.4.1</b> Многофакторный дисперсионный анализ со взаимодействием в R</a></li>
</ul></li>
<li class="chapter" data-level="9.5" data-path="anova-a-k-a-дисперсионный-анализ.html"><a href="anova-a-k-a-дисперсионный-анализ.html#важность-аггрегации-данных"><i class="fa fa-check"></i><b>9.5</b> Важность аггрегации данных</a></li>
<li class="chapter" data-level="9.6" data-path="anova-a-k-a-дисперсионный-анализ.html"><a href="anova-a-k-a-дисперсионный-анализ.html#итоги"><i class="fa fa-check"></i><b>9.6</b> Итоги</a></li>
</ul></li>
<li class="chapter" data-level="10" data-path="регрессионный-анализ.html"><a href="регрессионный-анализ.html"><i class="fa fa-check"></i><b>10</b> Регрессионный анализ</a>
<ul>
<li class="chapter" data-level="10.1" data-path="регрессионный-анализ.html"><a href="регрессионный-анализ.html#введение-1"><i class="fa fa-check"></i><b>10.1</b> Введение</a></li>
<li class="chapter" data-level="10.2" data-path="регрессионный-анализ.html"><a href="регрессионный-анализ.html#парная-линейная-регрессия"><i class="fa fa-check"></i><b>10.2</b> Парная линейная регрессия</a></li>
<li class="chapter" data-level="10.3" data-path="регрессионный-анализ.html"><a href="регрессионный-анализ.html#мотематика"><i class="fa fa-check"></i><b>10.3</b> Мотематика</a>
<ul>
<li class="chapter" data-level="10.3.1" data-path="регрессионный-анализ.html"><a href="регрессионный-анализ.html#а-как-это-будет-в-r"><i class="fa fa-check"></i><b>10.3.1</b> А как это будет в R</a></li>
<li class="chapter" data-level="10.3.2" data-path="регрессионный-анализ.html"><a href="регрессионный-анализ.html#подставляем-значения-в-формулу-регрессии"><i class="fa fa-check"></i><b>10.3.2</b> Подставляем значения в формулу регрессии</a></li>
<li class="chapter" data-level="10.3.3" data-path="регрессионный-анализ.html"><a href="регрессионный-анализ.html#количество-объяснённой-дисперсии"><i class="fa fa-check"></i><b>10.3.3</b> Количество объяснённой дисперсии</a></li>
<li class="chapter" data-level="10.3.4" data-path="регрессионный-анализ.html"><a href="регрессионный-анализ.html#посмотреть-на-остатки"><i class="fa fa-check"></i><b>10.3.4</b> Посмотреть на остатки</a></li>
</ul></li>
<li class="chapter" data-level="10.4" data-path="регрессионный-анализ.html"><a href="регрессионный-анализ.html#другие-виды-предикторов-и-их-комбинации"><i class="fa fa-check"></i><b>10.4</b> Другие виды предикторов и их комбинации</a>
<ul>
<li class="chapter" data-level="10.4.1" data-path="регрессионный-анализ.html"><a href="регрессионный-анализ.html#категориальный-предиктор"><i class="fa fa-check"></i><b>10.4.1</b> Категориальный предиктор</a></li>
<li class="chapter" data-level="10.4.2" data-path="регрессионный-анализ.html"><a href="регрессионный-анализ.html#количественный-и-категориальный-предиктор-вместе"><i class="fa fa-check"></i><b>10.4.2</b> Количественный и категориальный предиктор вместе</a></li>
</ul></li>
<li class="chapter" data-level="10.5" data-path="регрессионный-анализ.html"><a href="регрессионный-анализ.html#два-количественных-предиктора"><i class="fa fa-check"></i><b>10.5</b> Два количественных предиктора</a></li>
</ul></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">АнДан 2021: стартовая программа</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="регрессионный-анализ" class="section level1" number="10">
<h1><span class="header-section-number">10</span> Регрессионный анализ</h1>
<style type="text/css">
.spoiler {
  visibility: hidden;
  background: #ffffe0
}

.spoiler::before {
  visibility: visible;
  background: cyan;
  content: "Спойлер! Наведите, чтобы увидеть ответ"
}

.spoiler:hover {
  visibility: visible;
}

.spoiler:hover::before {
  display: none;
}
</style>
<div id="введение-1" class="section level2" number="10.1">
<h2><span class="header-section-number">10.1</span> Введение</h2>
<p>Дисклеймер: в этом файле под некоторыми заданиями есть текстовые ответы (без кода), скрытые под синенькой плашкой “спойлер”. Она срабатывает при наведённом на неё курсоре:</p>
<p><span class="spoiler">Если вы случайно проспойлерили себе ответ, не расстраивайтесь, вам всё ещё нужно написать код, который будет выдавать этот ответ :)</span></p>
<p>Итак, регрессия. Это метод, позволяющий исследовать взаимосвязь между одной зависимой переменной <span class="math inline">\(y_i\)</span> и одной или несколькими независимыми переменными <span class="math inline">\(x_i\)</span>.</p>
<p>В этом материале мы разберём, как построить парную и множественную линейные регрессии в R и что потом со всем этим делать.</p>
</div>
<div id="парная-линейная-регрессия" class="section level2" number="10.2">
<h2><span class="header-section-number">10.2</span> Парная линейная регрессия</h2>
</div>
<div id="мотематика" class="section level2" number="10.3">
<h2><span class="header-section-number">10.3</span> Мотематика</h2>
<p><img src="https://sun9-55.userapi.com/zAw1CCGDk5UIXXx-C2ljiEibLooC5dDXPDSBXQ/Zw9PIkO2Eb4.jpg" /></p>
<p>В основе регрессионного анализа лежит метод наименьших квадратов. Формула регрессии выглядит так:</p>
<p><span class="math display">\[y_i = \beta_0 + \beta_1 x_i + \epsilon_i\]</span></p>
<p>где <span class="math inline">\(\beta_0\)</span> и <span class="math inline">\(\beta_1\)</span> – это коэффициенты регрессии, неизвестные параметры, которые мы хотим найти, а <span class="math inline">\(\epsilon_i\)</span> – ошибка, или расстояние от настоящего значения <span class="math inline">\(y_i\)</span> до предсказанного.</p>
<p>Предсказанный игрек обозначается так: <span class="math inline">\(\hat{y}_i\)</span></p>
<p>А считается так:</p>
<p><span class="math display">\[\hat{y}_i = \beta_0 + \beta_1 x_i\]</span>
Мы хотим оценить неизвестные беты и провести регрессионную прямую так, чтобы минимизировать суммарную ошибку.</p>
<p><img src="https://miro.medium.com/max/1050/0*QG8dIxNTaBH7Qrxq" /></p>
<p>На картинке ниже ошибки – это вертикальные красные линии – расстояния до прямой. Если просто их суммировать, легко получить нулевую ошибку, т.к. эти расстояния имеют разные знаки. Поэтому придумали возводить ошибку в квадрат и искать такие параметры регрессии, которые минимизировали бы сумму квадратов ошибок – это и есть метод наименьших квадратов (МНК).</p>
<p><img src="https://risk-engineering.org/static/img/large/OLS.png" /></p>
<p>Из уравнения регрессии можно выразить формулу ошибки</p>
<p><span class="math display">\[\epsilon_i = y_i - \beta_0 - \beta_1 x_i \\ \]</span>
Откуда сумма квадратов ошибок:</p>
<p><span class="math display">\[\sum \epsilon_i^2 = \sum(y_i - \beta_0 - \beta_1 x_i)^2 \\ \]</span></p>
<p>Далее эту штуку можно минимизировать по параметрам <span class="math inline">\(\beta\)</span> (приравнять производную к нулю, и вот это вот всё) и вывести формулы для коэффициентов регрессии. Решение есть вот <a href="https://warwick.ac.uk/fac/soc/economics/staff/vetroeger/teaching/po906_week567.pdf">тут</a> на страницах 7-9 (правда работает это только для случая парной регрессии)</p>
<p><img src="https://www.meme-arsenal.com/memes/290f82ae820c34bda9a5e3c5ce4a65bc.jpg" /></p>
<p>А мы переходим к разделу</p>
<div id="а-как-это-будет-в-r" class="section level3" number="10.3.1">
<h3><span class="header-section-number">10.3.1</span> А как это будет в R</h3>
<p>В R для линейной регрессии применяется функция <code>lm()</code> (linear model)</p>
<p>Попробуем на наших данных посмотреть на связь великолепности с размером обуви.</p>
<p>Как устроена функция <code>lm()</code>: удобнее всего прописать через запятую</p>
<ul>
<li>формулу в виде <code>y ~ x</code> (в случае множественной регрессии будет <code>y ~ x1 + x2</code> и так далее)</li>
<li>данные в виде <code>data=df</code></li>
</ul>
<p>Можно и не выписывать данные отдельно, а написать через доллар <code>df$y ~ df$x</code> но когда у вас много переменных или датасет называется каким-то длинным словом, это будет уже тяжелее</p>
<div class="sourceCode" id="cb557"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb557-1"><a href="регрессионный-анализ.html#cb557-1" aria-hidden="true" tabindex="-1"></a>df <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">&#39;about_us_eng.csv&#39;</span>)</span></code></pre></div>
<div class="sourceCode" id="cb558"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb558-1"><a href="регрессионный-анализ.html#cb558-1" aria-hidden="true" tabindex="-1"></a><span class="fu">lm</span>(gorgeous<span class="sc">~</span>shoe_size, <span class="at">data=</span>df)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = gorgeous ~ shoe_size, data = df)
## 
## Coefficients:
## (Intercept)    shoe_size  
##     19.1978      -0.2881</code></pre>
<p>Функция <code>lm()</code> выдаёт такую вот простенькую выдачу, где показана формула нашей регрессии и оценки коэффициентов <span class="math inline">\(\beta_0\)</span> (Intercept) и <span class="math inline">\(\beta_1\)</span> <code>shoe_size</code>.</p>
<p>Получается наша итоговая формула для предсказанного игрека выглядит так:</p>
<p><span class="math display">\[\hat{y}_i = 19.1977978 - 0.2881108 x_i\]</span></p>
<p>А вот наша регрессия на картиночке:</p>
<p><img src="andan_2021_files/figure-html/unnamed-chunk-344-1.png" width="672" /></p>
<p>Интерсепт отвечает за значение зависимой переменной в нуле: то есть при нулевом размере обуви великолепность человека будет аж 19 пунктов :)</p>
<p>Если вспомнить наш опрос, такого варианта ответа там не было, получается, наша регрессия предсказывает слишком большие значения?</p>
<p>Не совсем. Если подставлять в формулу регрессии осмысленные значения размера обуви, то великолепность окажется в рамках нормы. Для среднестатистических взрослых людей наша регрессия предсказывает нормальные значения великолепности, но вообще в реальности проблема с выходом за рамки допустимых значений существует, и для некоторых специфически распределённых зависимых переменных линейная регрессия не подходит (например, для бинарного игрека используется логистическая, а чтобы ограничить значения предсказаний с одной стороны существует тобит-регрессия).</p>
<p>Но вернёмся к нашей модели. R позволяет записать регрессию в переменную, а потом посмотреть на более подробную выдачу с помощью комманды <code>summary()</code></p>
<div class="sourceCode" id="cb560"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb560-1"><a href="регрессионный-анализ.html#cb560-1" aria-hidden="true" tabindex="-1"></a>model <span class="ot">&lt;-</span> <span class="fu">lm</span>(gorgeous<span class="sc">~</span>shoe_size, <span class="at">data=</span>df)</span>
<span id="cb560-2"><a href="регрессионный-анализ.html#cb560-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = gorgeous ~ shoe_size, data = df)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -4.5377 -1.1734  0.4707  1.7504  3.1910 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)   
## (Intercept)  19.1978     5.5055   3.487   0.0014 **
## shoe_size    -0.2881     0.1375  -2.095   0.0439 * 
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 2.104 on 33 degrees of freedom
## Multiple R-squared:  0.1174, Adjusted R-squared:  0.09068 
## F-statistic: 4.391 on 1 and 33 DF,  p-value: 0.04389</code></pre>
<p>Что у нас тут есть:</p>
<p>Во-первых, добавились p-value и значимость коэффициентов. Что это такое?</p>
<p>Значимость – это результат проверки гипотезы о равенстве коэффициента нулю. Эта гипотеза проверяется с помощью t-теста, который мы обсуждали в материале про статистические критерии.</p>
<p>Нулевая гипотеза: коэффициент бета равен нулю, то есть между переменными <span class="math inline">\(x\)</span> и <span class="math inline">\(y\)</span> нет взаимосвязи. Значим ли интерсепт, в большинстве случаев неважно (разве что вам принципиально знать, что люди с нулевым размером обуви имеют ненулевую великолепность))</p>
<p>p-value показывает вероятность отвергнуть верную нулевую гипотезу, то есть найти связь там где её нет. Чем оно меньше, тем лучше. Звёздочки показывают, что p-value меньше одного из трёх конвенциональных значений: 0.05, 0.01 и 0.001. А наши звёздочки говорят нам, что коэффициент <span class="math inline">\(\beta_1\)</span> значим на уровне 0.05, то есть по нашим данным можно сказать, что есть значимая отричательная связь между размером обуви и великолепностью.</p>
</div>
<div id="подставляем-значения-в-формулу-регрессии" class="section level3" number="10.3.2">
<h3><span class="header-section-number">10.3.2</span> Подставляем значения в формулу регрессии</h3>
<p>Что значит “подставлять в формулу регрессии осмысленные значения”? Формула, которую мы увидели выше, описывает линейную взаимосвязь между x и y. Соответственно, если подставить какой-нибудь предиктор икс (<span class="math inline">\(x_i\)</span>) в формулу и подсчитать, то результат (<span class="math inline">\(\hat{y}_i\)</span>) это предсказанное значение. Например: если мы взяли с улицы человека и спросили, какой у него размер обуви равен 39, то, согласно предсказаниям нашей модели, великолепность равна 7.96:</p>
<div class="sourceCode" id="cb562"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb562-1"><a href="регрессионный-анализ.html#cb562-1" aria-hidden="true" tabindex="-1"></a><span class="fl">19.1977978</span> <span class="sc">-</span> <span class="fl">0.2881108</span><span class="sc">*</span><span class="dv">39</span></span></code></pre></div>
<pre><code>## [1] 7.961477</code></pre>
<p>Значения параметров 19.1977978 и 0.2881108 мы взяли из результата работы функции <code>lm()</code>. Но, конечно, считать руками это не путь воина (то есть, надо быть готовым/ой это сделать, но сначала всегда пытаться избежать))).</p>
<p>Во-первых, коэффициенты модели можно достать вот так:</p>
<div class="sourceCode" id="cb564"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb564-1"><a href="регрессионный-анализ.html#cb564-1" aria-hidden="true" tabindex="-1"></a>model<span class="sc">$</span>coefficients</span></code></pre></div>
<pre><code>## (Intercept)   shoe_size 
##  19.1977978  -0.2881108</code></pre>
<p>А главное, можно использовать функцию <code>predict()</code>. Она принимает на вход, во-первых, нашу модель (результат функции <code>lm()</code>, сохранённый в переменную). Если дать ей только нашу модель и ничего больше, она вернёт предсказанное значение для каждый строки (=каждого респондента) в нашем датасете:</p>
<div class="sourceCode" id="cb566"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb566-1"><a href="регрессионный-анализ.html#cb566-1" aria-hidden="true" tabindex="-1"></a><span class="fu">predict</span>(model)</span></code></pre></div>
<pre><code>##        1        2        3        4        5        6        7        8 
## 8.249588 6.809034 8.249588 8.249588 7.097145 7.961477 7.097145 7.385256 
##        9       10       11       12       13       14       15       16 
## 8.249588 8.249588 7.961477 8.537699 8.825810 6.232813 7.961477 8.825810 
##       17       18       19       20       21       22       23       24 
## 6.809034 7.673367 6.232813 7.961477 6.232813 7.385256 8.249588 6.809034 
##       25       26       27       28       29       30       31       32 
## 9.113921 7.673367 7.673367 6.809034 8.249588 7.961477 7.673367 8.249588 
##       33       34       35 
## 7.529311 6.809034 7.961477</code></pre>
<p>А можно ещё сделать новую таблицу с данными, дать её на вход в аргументе <code>newdata</code>, и тогда <code>predict()</code> воспользуется выведенной формулой, чтобы предсказать значения для этих данных. Важно! Названия колонки в новой таблице и в той, которую вы использовали в lm(), должны совпадать.</p>
<div class="sourceCode" id="cb568"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb568-1"><a href="регрессионный-анализ.html#cb568-1" aria-hidden="true" tabindex="-1"></a>newdf <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">shoe_size =</span> <span class="dv">33</span>) <span class="co">#создадим новую таблицу с одной колонкой shoe_size и значением 33.</span></span>
<span id="cb568-2"><a href="регрессионный-анализ.html#cb568-2" aria-hidden="true" tabindex="-1"></a><span class="fu">predict</span>(model, <span class="at">newdata =</span> newdf)</span></code></pre></div>
<pre><code>##        1 
## 9.690142</code></pre>
<p>Вот такое значение замечательности предсказывает наша модель для людей, у которых 33 размер обуви.</p>
</div>
<div id="количество-объяснённой-дисперсии" class="section level3" number="10.3.3">
<h3><span class="header-section-number">10.3.3</span> Количество объяснённой дисперсии</h3>
<p>Важный показатель того, насколько наша модель хорошо объясняет данные, это <span class="math inline">\(R^2\)</span>, или процент объяснённой дисперсии. Мы можем увидить его внизу выдачи <code>summary(model)</code>:</p>
<div class="sourceCode" id="cb570"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb570-1"><a href="регрессионный-анализ.html#cb570-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = gorgeous ~ shoe_size, data = df)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -4.5377 -1.1734  0.4707  1.7504  3.1910 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)   
## (Intercept)  19.1978     5.5055   3.487   0.0014 **
## shoe_size    -0.2881     0.1375  -2.095   0.0439 * 
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 2.104 on 33 degrees of freedom
## Multiple R-squared:  0.1174, Adjusted R-squared:  0.09068 
## F-statistic: 4.391 on 1 and 33 DF,  p-value: 0.04389</code></pre>
<p>Или вытащить из <code>summary(model)</code> с помощью доллара:</p>
<div class="sourceCode" id="cb572"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb572-1"><a href="регрессионный-анализ.html#cb572-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model)<span class="sc">$</span>r.squared</span></code></pre></div>
<pre><code>## [1] 0.1174273</code></pre>
<p><span class="math inline">\(R^2\)</span> показывает, какой процент дисперсии - то есть, шума в данных - объясняется нашим предиктором. В нашей модели размер обуви объясняет примерно</p>
<div class="sourceCode" id="cb574"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb574-1"><a href="регрессионный-анализ.html#cb574-1" aria-hidden="true" tabindex="-1"></a><span class="fu">paste0</span>(<span class="fu">round</span>(<span class="fu">summary</span>(model)<span class="sc">$</span>r.squared, <span class="dv">2</span>)<span class="sc">*</span><span class="dv">100</span>, <span class="st">&#39;%&#39;</span>)</span></code></pre></div>
<pre><code>## [1] &quot;12%&quot;</code></pre>
<p>дисперсии в оценке великолепности. В общем и целом модель с более высоким <span class="math inline">\(R^2\)</span> лучше, но при этом модель с б<em>о</em>льшим количеством предикторов будет всегда по умолчанию иметь б<em>о</em>льший <span class="math inline">\(R^2\)</span>, так что сравнивать с помощью <span class="math inline">\(R^2\)</span> разные модели мы не советуем.</p>
<div class="rmdtask">
<p>
ЗАДАЧКА
</p>
<p>
Посчитайте предсказанную великолепность людей с минимальным и максимальным размером обуви
</p>
</div>
<p><span class="spoiler">Минимальные и максимальные размеры – 35 и 45, а ответы – 9.113921 и 6.232813 соответственно</span></p>
<div class="figure">
<img src="https://cdn.ebaumsworld.com/thumbs/natural/gallery/2242139/86407354.jpg" alt="" />
<p class="caption">Поздравляем! Вы построили свою первую регрессию и проинтерпретировали ВООБЩЕ ВСЕ в выдаче (ну почти))</p>
</div>
</div>
<div id="посмотреть-на-остатки" class="section level3" number="10.3.4">
<h3><span class="header-section-number">10.3.4</span> Посмотреть на остатки</h3>
<p>Одно из базовых допущений линейной регрессии - что остатки, или ошибки, распределены нормально. Остатки это разница между реальным значением зависимой переменной (здесь великолепности) и значением, которое предсказывает наша модель. Остатки можно “вынуть” из объекта с моделью:</p>
<div class="sourceCode" id="cb576"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb576-1"><a href="регрессионный-анализ.html#cb576-1" aria-hidden="true" tabindex="-1"></a>model<span class="sc">$</span>residuals</span></code></pre></div>
<pre><code>##           1           2           3           4           5           6 
##  1.75041176  3.19096566 -1.24958824  1.75041176 -1.09714512  2.03852254 
##           7           8           9          10          11          12 
##  0.90285488  0.61474410 -1.24958824  0.75041176 -2.96147746 -4.53769902 
##          13          14          15          16          17          18 
##  1.17419020  1.76718721  0.03852254  1.17419020  1.19096566 -0.67336668 
##          19          20          21          22          23          24 
## -3.23281279  2.03852254 -0.23281279 -3.38525590 -1.24958824 -3.80903434 
##          25          26          27          28          29          30 
## -0.11392058  2.32663332 -3.67336668  3.19096566  1.75041176 -0.96147746 
##          31          32          33          34          35 
##  2.32663332  0.75041176  0.47068871  0.19096566 -0.96147746</code></pre>
<p>То есть, здесь каждое число это разница между реальным великолепием каждого респондента, и великолепием, которое предсказывает наша модель :))</p>
<p>Мы можем построить уже дорогую и знакомую нам гистограмму, чтобы проверить, как у них там с нормальностью:</p>
<div class="sourceCode" id="cb578"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb578-1"><a href="регрессионный-анализ.html#cb578-1" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(model<span class="sc">$</span>residuals)</span></code></pre></div>
<p><img src="andan_2021_files/figure-html/unnamed-chunk-355-1.png" width="672" />
Или проверить их на нормальность с помощью формального теста, например, Шапиро-Уилкс:</p>
<div class="sourceCode" id="cb579"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb579-1"><a href="регрессионный-анализ.html#cb579-1" aria-hidden="true" tabindex="-1"></a><span class="fu">shapiro.test</span>(model<span class="sc">$</span>residuals)</span></code></pre></div>
<pre><code>## 
##  Shapiro-Wilk normality test
## 
## data:  model$residuals
## W = 0.94169, p-value = 0.06301</code></pre>
<p>Здесь мои графические выводы (да норм) и вывод Шапиро-Уилка совпадают. Но на самом деле на больших выборках (хотя бы &gt;30) линейная регрессия устойчива к не нормально распределённым данным. Если у вас на гистограмме симметричное распределение с одним пиком, то вы в безопасности.</p>
<p><img src="https://moidrujok.ru/wp-content/uploads/2020/04/eto-norma.jpg" /></p>
<p>О других допущениях можно почитать вот <a href="https://www.statology.org/linear-regression-assumptions/">туть</a></p>
<div class="rmdtask">
<p>
Придумайте гипотезу о взаимосвязи двух количественных переменных в нашем датасете. Проверьте эту гипотезу с помощью линейной регрессии :) Проверьте остатки на нормальность.
</p>
</div>
</div>
</div>
<div id="другие-виды-предикторов-и-их-комбинации" class="section level2" number="10.4">
<h2><span class="header-section-number">10.4</span> Другие виды предикторов и их комбинации</h2>
<div id="категориальный-предиктор" class="section level3" number="10.4.1">
<h3><span class="header-section-number">10.4.1</span> Категориальный предиктор</h3>
<p>Можно построить регрессию <span class="math inline">\(y\)</span> на одну категориальную переменную.</p>
<p>Давайте попробуем предсказать связь великолепности с наличием кошки (создадим для этого переменную “cat_owner”)</p>
<div class="sourceCode" id="cb581"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb581-1"><a href="регрессионный-анализ.html#cb581-1" aria-hidden="true" tabindex="-1"></a>df<span class="sc">$</span>cat_owner <span class="ot">&lt;-</span> <span class="fu">ifelse</span>(df<span class="sc">$</span>cats <span class="sc">!=</span> <span class="dv">0</span>, <span class="st">&#39;yes&#39;</span>,<span class="st">&#39;no&#39;</span>)</span>
<span id="cb581-2"><a href="регрессионный-анализ.html#cb581-2" aria-hidden="true" tabindex="-1"></a>model_cat <span class="ot">=</span> <span class="fu">lm</span>(<span class="at">data=</span>df, gorgeous<span class="sc">~</span>cat_owner)</span>
<span id="cb581-3"><a href="регрессионный-анализ.html#cb581-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model_cat)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = gorgeous ~ cat_owner, data = df)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -4.4500 -1.4500  0.3333  1.5500  3.3333 
## 
## Coefficients:
##              Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)    6.6667     0.5285  12.613 3.59e-14 ***
## cat_owneryes   1.7833     0.6992   2.551   0.0156 *  
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 2.047 on 33 degrees of freedom
## Multiple R-squared:  0.1647, Adjusted R-squared:  0.1394 
## F-statistic: 6.505 on 1 and 33 DF,  p-value: 0.01558</code></pre>
<p>При наличии категориального предиктора R создает k-1 дамми-переменную, каждая из которых принимает значение 1 в своей категории и 0 во всех остальных.</p>
<p>То есть в случае с нашими кошками в данных существует две категории: “есть кошки” и “нет кошек”. Значит в регрессии будет одна дамми-переменная, которая равна единице, если кошки есть.</p>
<p>Смысл этого, возможно, будет более понятен из формул, но если что, про дамми можно почитать вот например <a href="https://www.displayr.com/what-are-dummy-variables/">здесь</a></p>
<p>В summary значения категорий приписываются к названию изначальной переменной – в нашем примере получилось “cat_owneryes”. Посмотрим еще раз как это выглядит в формуле:</p>
<p><span class="math display">\[\hat{y}_i = \beta_0 + \beta_1 x_i\]</span>
Помним, что <span class="math inline">\(x_i\)</span> принимает значение 1 для кошатников и 0 для не-кошатников. Соответственно, для кошатников уравнение будет выглядеть так:</p>
<p><span class="math inline">\(\hat{y}_i = \beta_0 + \beta_1 \cdot 1 \Leftrightarrow \hat{y}_i = \beta_0 + \beta_1\)</span>,</p>
<p>а для не-кошатников:</p>
<p><span class="math inline">\(\hat{y}_i = \beta_0 + \beta_1 \cdot 0 \Leftrightarrow \hat{y}_i = \beta_0\)</span></p>
<p>Сами коэффициенты в выдаче интерпретируются так: средняя великолепность не-кошатников равна 6.6667 (intercept), а средняя великолепность кошатников на 1.7833 больше (1.7833 + 6.6667 = 8.45). Если обратить внимание на значимость, кошатники в среднем <em>значимо</em> более великолепны, чем не-кошатники.</p>
<p>Если же мы вставим в регрессию первоначальный предиктор про кошек, получится вот что:</p>
<div class="sourceCode" id="cb583"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb583-1"><a href="регрессионный-анализ.html#cb583-1" aria-hidden="true" tabindex="-1"></a>model_cat2 <span class="ot">=</span> <span class="fu">lm</span>(<span class="at">data=</span>df, gorgeous<span class="sc">~</span>cats)</span>
<span id="cb583-2"><a href="регрессионный-анализ.html#cb583-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model_cat2)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = gorgeous ~ cats, data = df)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -4.3077 -1.5000  0.3333  1.5962  3.3333 
## 
## Coefficients:
##                          Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)                6.6667     0.5489  12.145 4.13e-13 ***
## cats1                      1.6410     0.8056   2.037   0.0506 .  
## cats2                      1.8333     1.1964   1.532   0.1359    
## catsmore than 2            3.3333     2.1958   1.518   0.1395    
## catsthis is too personal   1.8333     1.6004   1.146   0.2610    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 2.126 on 30 degrees of freedom
## Multiple R-squared:  0.1809, Adjusted R-squared:  0.07164 
## F-statistic: 1.656 on 4 and 30 DF,  p-value: 0.1862</code></pre>
<p>И здесь все категории нужно интерпретировать <em>по отдельности, в сравнении с базовой</em> (в нашем случае базовая категория – 0 кошек).</p>
<p>Так например, люди с одной кошкой в среднем на 1.64 более великолепны, чем люди без кошек, и этот предиктор значим на уровне 0.1. А люди с двумя кошками на 1.83 более великолепны, чем люди без кошек, но разница между ними незначима.</p>
<div class="rmdtask">
<p>
ЗАДАЧКА
</p>
<p>
Постройте регрессию роста на переменную “выбор горячего напитка”. Какой напиток пьют самые высокие в среднем люди?
</p>
</div>
<p><img src="https://i.forfun.com/jsk254e2.jpeg" /></p>
</div>
<div id="количественный-и-категориальный-предиктор-вместе" class="section level3" number="10.4.2">
<h3><span class="header-section-number">10.4.2</span> Количественный и категориальный предиктор вместе</h3>
<p>Самый главный кайф регрессии в том, что в качестве предикторов можно засунуть много переменных сразу. Давайте для начала засунем две – “размер обуви” и “есть кошка”</p>
<div class="sourceCode" id="cb585"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb585-1"><a href="регрессионный-анализ.html#cb585-1" aria-hidden="true" tabindex="-1"></a>model_num_cat <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="at">data=</span>df, gorgeous <span class="sc">~</span> shoe_size <span class="sc">+</span> cat_owner)</span>
<span id="cb585-2"><a href="регрессионный-анализ.html#cb585-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model_num_cat)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = gorgeous ~ shoe_size + cat_owner, data = df)
## 
## Residuals:
##    Min     1Q Median     3Q    Max 
## -4.995 -1.439  0.339  1.450  2.748 
## 
## Coefficients:
##              Estimate Std. Error t value Pr(&gt;|t|)   
## (Intercept)   15.6980     5.4616   2.874  0.00714 **
## shoe_size     -0.2223     0.1338  -1.661  0.10648   
## cat_owneryes   1.5203     0.6994   2.174  0.03724 * 
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 1.995 on 32 degrees of freedom
## Multiple R-squared:  0.231,  Adjusted R-squared:  0.1829 
## F-statistic: 4.805 on 2 and 32 DF,  p-value: 0.01497</code></pre>
<p>Судя по выдаче, предиктор “размер обуви” перестал быть значимым совсем, то есть изменение размера обуви на единицу никак не сказывается на изменении великолепности.</p>
<p>В то же время люди, имеющие кошек, по-прежнему значимо более великолепны, чем не имеющие кошек.</p>
<p>А вот как наши точки и регрессионные прямые будут выглядеть на графике:</p>
<p><img src="andan_2021_files/figure-html/unnamed-chunk-362-1.png" width="672" /></p>
<p>Это параллельные регрессионные прямые. Они отличаются только на параметр <span class="math inline">\(\beta_0\)</span></p>
<p>Чтобы разрешить прямым не быть параллельными, можно добавить взаимодействие!</p>
<p>Формула внутри <code>lm</code> поменяется: между предикторами будет не плюс, а умножение:</p>
<div class="sourceCode" id="cb587"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb587-1"><a href="регрессионный-анализ.html#cb587-1" aria-hidden="true" tabindex="-1"></a>model_inter_cut <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="at">data=</span>df, gorgeous <span class="sc">~</span> shoe_size <span class="sc">*</span> cat_owner)</span>
<span id="cb587-2"><a href="регрессионный-анализ.html#cb587-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model_inter_cut)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = gorgeous ~ shoe_size * cat_owner, data = df)
## 
## Residuals:
##    Min     1Q Median     3Q    Max 
## -4.519 -1.449  0.665  1.509  3.120 
## 
## Coefficients:
##                        Estimate Std. Error t value Pr(&gt;|t|)   
## (Intercept)             23.2932     7.5061   3.103  0.00406 **
## shoe_size               -0.4092     0.1843  -2.220  0.03386 * 
## cat_owneryes           -13.7388    10.5583  -1.301  0.20277   
## shoe_size:cat_owneryes   0.3812     0.2632   1.448  0.15757   
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 1.961 on 31 degrees of freedom
## Multiple R-squared:  0.2797, Adjusted R-squared:   0.21 
## F-statistic: 4.013 on 3 and 31 DF,  p-value: 0.01597</code></pre>
<p>Коэффициентов стало уже даже больше, чем переменных!</p>
<p>Давайте по порядку. Размер обуви снова стал значимым. Но не для всех! Только для группы не-кошатников. Среди не-кошатников увеличение размера обуви на единицу связано со снижением великолепности на 0.4.</p>
<p>Следующий предиктор – наличие кошки. Это дополнительный интерсепт для кошатников. Он означает, что их личная регрессионная прямая будет выходить из точки на 13 единиц ниже. Другими словами, это разница между кошатниками и не-кошатниками <em>с нулевым размером обуви</em> (в нашем случае незначимая).</p>
<p>Регрессионная прямая у кошатников тоже будет личная, ее наклон будет таким: -0.41 + 0.38 = -0.03 (коэфф. не-кошатников плюс коэфф. кошатников). То есть личная линия кошатников будет практически параллельна оси икс.</p>
<p>Проверим на картинке:</p>
<p><img src="andan_2021_files/figure-html/unnamed-chunk-364-1.png" width="672" /></p>
<p>Всё как мы и предсказывали! Личная линия кошатников (синяя) начинается <em>ниже</em> линии не-кошатников (если мысленно продлить обе линии влево до нуля по оси икс), и при этом она более пологая.</p>
<p>Красная же линия, наоборот, получилась более наклонной, чем в регрессии без взаимодействия, и во всей регрессионной модели только один этот наклон оказался значимым (ну и еще интерсепт не-кошатников).</p>
<p>Вспомним, что когда мы строили регрессию на всей выборке, мы получили значимую отрицательную взаимосвязь между размером обуви и великолепностью. Теперь, посмотрев на регрессионные прямые внутри групп, можем сделать вывод, что тот отрицательный эффект был обусловлен только не-кошатниками, в группе кошатников он не выявляется.</p>
<div class="rmdtask">
<p>
ЗАДАЧКА
</p>
<p>
Проверьте связь между великолепностью и размером обуви для групп: 0 или 1 родственник vs. 2 и более родственников. В какой группе связь положительная? Насколько именно увеличится великолепность с увеличением размера обуви на 1?
</p>
</div>
<p><span class="spoiler">У людей, которые имеют больше одного брата или сестры, великолепность увеличивается вместе с размером обуви примерно на 0.3.</span></p>
<div class="figure">
<img src="https://gifki.info/uploads/posts/2017-01/1485245017_39-pozdravlyayu-vseh.gif" alt="" />
<p class="caption">Поздравляю! Это почти совсем всё про регрессии!</p>
</div>
</div>
</div>
<div id="два-количественных-предиктора" class="section level2" number="10.5">
<h2><span class="header-section-number">10.5</span> Два количественных предиктора</h2>
<p>Ну и наконец мы можем добавить в регрессию два (а то и больше!) количественных предикторов. Давайте попробуем предсказать размер обуви по длине волос и росту.</p>
<div class="sourceCode" id="cb589"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb589-1"><a href="регрессионный-анализ.html#cb589-1" aria-hidden="true" tabindex="-1"></a>model_num <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="at">data=</span>df, shoe_size <span class="sc">~</span> hair_length <span class="sc">+</span> height)</span>
<span id="cb589-2"><a href="регрессионный-анализ.html#cb589-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model_num)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = shoe_size ~ hair_length + height, data = df)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -4.1670 -0.6979 -0.2558  1.0798  2.7713 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)  0.69847    6.74704   0.104   0.9182    
## hair_length -0.04672    0.02327  -2.008   0.0534 .  
## height       0.23489    0.03788   6.200 6.95e-07 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 1.468 on 31 degrees of freedom
##   (1 observation deleted due to missingness)
## Multiple R-squared:  0.6789, Adjusted R-squared:  0.6582 
## F-statistic: 32.78 on 2 and 31 DF,  p-value: 2.251e-08</code></pre>
<p>Ура, снова нормальное количество коэффициентов :)</p>
<p>Проинтерпретируем же их:</p>
<ul>
<li><p>при увеличении длины волос на сантиметр размер обуви в среднем уменьшается на 0.047 <em>при фиксированном значении роста</em>. То есть среди людей <em>с одинаковым ростом</em> те, у кого длиннее волосы, будут в среднем иметь чуть меньший размер обуви. Эта связь очень слабо значима, только на уровне 0.1</p></li>
<li><p>при увеличении роста на сантиметр размер обуви в среднем увеличивается на 0.23 <em>при фиксированном значении длины волос</em>. Эта связь значима на уровне 0.001; другими словами, размер обуви сильно связан с ростом</p></li>
</ul>
<p>Ну и напоследок:</p>
<div class="rmdtask">
<p>
ФИНАЛЬНАЯ ЗАДАЧЕЧКА
</p>
<p>
Загрузите по ссылкам два датесета:
</p>
<p>
dfmale &lt;- read.csv(‘<a href="https://people.sc.fsu.edu/~jburkardt/datasets/triola/mhealth.csv" class="uri">https://people.sc.fsu.edu/~jburkardt/datasets/triola/mhealth.csv</a>’)
</p>
<p>
dffemale &lt;- read.csv(‘<a href="https://people.sc.fsu.edu/~jburkardt/datasets/triola/fhealth.csv" class="uri">https://people.sc.fsu.edu/~jburkardt/datasets/triola/fhealth.csv</a>’)
</p>
<p>
Это два датасета с результатами прохождения медицинского обследования для мужчин и женщин. В них одинаковые по смыслу колонки, но с немного разными названиями. Первая колонка – это просто айди каждого человека.
</p>
<p>
Для начала придумайте, как их вертикально склеить. Затем попробуйте найти модель, которая с наилучшим R-квадратом будет предсказывать, например, уровень холестерина. Финальную модель проверьте на нормальность остатков.
</p>
</div>
<div class="figure">
<img src="https://www.meme-arsenal.com/memes/26113082cacca6345d17bc4e159f8de6.jpg" alt="" />
<p class="caption">До встречи на хакатоне!</p>
</div>

</div>
</div>












            </section>

          </div>
        </div>
      </div>
<a href="anova-a-k-a-дисперсионный-анализ.html" class="navigation navigation-prev navigation-unique" aria-label="Previous page"><i class="fa fa-angle-left"></i></a>

    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": false,
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/maria-srv/AnDan2021Start/edit/master/09_regressions.Rmd",
"text": "Edit"
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": null,
"toc": {
"collapse": "section"
},
"self_contained": true
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
